server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/my-db-test
    #url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    #username: cos
    username: sa
    #password: cos1234
    password:

        
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
#    show-sql: true
#    properties:
#      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

cos: 
  key: cos1234

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: TRACE
          
decorator:
  datasource:
    p6spy:
      enable-logging: true